=== hippietimelord/Popcorn/Popcorn/user.dtd
<!ELEMENT userprofile (user)>
<!ELEMENT user (image_url,name,birthday_date, address,
email, language,usr, position, telephone, branch
)>
<!ELEMENT image_url (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT birthday_date (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT language (#PCDATA)>
<!ELEMENT usr (#PCDATA)>
<!ELEMENT position (#PCDATA)>
<!ELEMENT telephone (#PCDATA)>
<!ELEMENT branch (#PCDATA)>

<!ATTLIST  user id CDATA #REQUIRED>
<!ATTLIST  branch address CDATA #REQUIRED>

=== hippietimelord/Popcorn/Popcorn/user.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="user.xsl" ?>
<!DOCTYPE userprofile SYSTEM "user.dtd">
<userprofile xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="user.xsd">
    
    <user id="001">
	<image_url>http://myswag.ru/wp-content/uploads/2018/02/avatar-user-teacher-312a499a08079a12-512x512.png</image_url>
        <name >&#160;&#160;&#160;&#160;&#160;Full name: &#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; Olivia Woods</name>
 <birthday_date>&#160;&#160;&#160;&#160;&#160;Date of Birth: &#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;11 Jan 1990</birthday_date>
<address>
		&#160;&#160;&#160;&#160;&#160;Address: &#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;
            &#160;123, Pandan Indah, Ampang, Kuala Lumpur
        </address>       
	   <email>&#160;&#160;&#160;&#160;&#160;Email: &#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;woods312@gmail.com</email>
        
		<language>&#160;&#160;&#160;&#160;&#160;Created: &#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; 12 May 2016</language>
        
		<usr>&#160;&#160;&#160;&#160;&#160;User ID: &#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;UPLTM00937</usr>
        
		
        <position>
          &#160;&#160;&#160;&#160;&#160;Ticket Bought: &#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;18
        </position>
        <telephone> &#160;&#160;&#160;&#160;&#160;Telephone No.: &#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;+8990833777</telephone>
        <branch address="240">&#160;&#160;&#160;&#160;&#160;Reward Point: &#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;210</branch>
        
        
    </user>
    
</userprofile>
